travis:
  secure:
    BINSTAR_TOKEN: OSNJrDloj8nlTU4DTDwhmS8ImkwNqL28lajfsIqFwhTvTvKXotznU19LHZrsLB+ZCBowrEdfzGC054UKGLOkVjyFpsvGBxkET1rdIipF32+wJwyyZL02MNXH1RLM8Jd/ok9L2v4GHR/ixAkYCr4EL2BfAXzftneBSogEHluYwJD38JPMUv3cpPR7q92Z+h1XE3ZGqnJKfhBhXrAfTfaYxpMdvQawNrPvxEQmXlFLGio+L8z4BgTN/4RIfi+jWWqUB+a26FhVcbvNhBCRQRN4o/Vr0ixHCwRlPJuhYbPXz9QyKS9XlgTWFAqpsHVqN1FEudcEuLktMk+DdtK9ryC+zpHsI18XD/1CcdYOC3jCkbLJijO8NjbPnHUn/L+2ZJHb7JCQcRQxKLTtsR6PPpPFa8qDfjjp/hXaW2BwrCLAdlOT3jmvVy+Ug9gdd5K/OPxcvDiqtNLGZuT6gB2plo1cI+4oD/Gj4fMnMhFzvw7xe0AETstBPonnyT/gzsg1QNqPAGbuyQf59VDiFfAbtvA4//HCLV1tTDxuZj+WYLvppuotQh0xKigcoAEDcQ1Cj8iNECz7gAAAYLcQwWA+suSn7MNPKF2kl5YfQwTYK9w9EsEj+pvew1CGdQWdQRXzKxd9c/a6IpaPNg933/5aQVKXyx1Bjnk7R5B8rtE+dGOTtSA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
