appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UQ4E4b+RoH/3/Z5czsWoqh35NO79Uc20n1n174ngo2eghBObP7S4CfIFViSsC6tKzlbxcf7749zqd+iDDaThLXgqbp8gMM9I99UOzthZ4r4LbJPllJo2H7mC1ZZDPaC0yQMuXBiXqHNoOPzIL8oR8Oj0rkCooiWaI0aAPQg6sspvkpg1QR7S+EO0SM+Ljdv3EK++NCRgHASlT4CRPFHGm7OGAURM30+rqPNI1g2gnAD+d2YVxmfHeWV+bFhEiBrYYHRJgnAQGR5oWvAe7RpIE/6roEdybwCebuqjk0aRmSY4KbyZsczgaI6aTXYtWIEOVTTCudoOSkdN6Pd5kMyRamT8WV6EQGmY0Zia8BKZaFieRIFHBleMUz9DTtsVyd9l0SQlDD7G9Sge3vTnFrIRUfJCVvt3bdA25KcfY4jhns82uuujljuJlkWSh7oj69PSar4yMtfV2yt7+VWoovywH0L/+sTLIal4eDiKzVwP/68Hsei5s2kmADsNJEuuAJ7zeozUhQFLPK2J8JkNeNFJtcb5VrR5Qm6VHu6YeCsm6KjMwEYldC6VKiC+jB0nKWH9KN8I1XT8FwTvJsLRaDltqoMu0XMfaHiQtY1WFwmIdwlbtNEXzLwhPGSZtQervJtDwNcqOdFnPzotibz+dXXWjh+8mBKorKwJ2CVnWfyHf70=}
bot:
  automerge: true
